// <auto-generated />
using System;
using DKCRM.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DKCRM.Data.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20230906112611_sondurum")]
    partial class sondurum
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DKCRM.Core.Entities.Address", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("CityCodeID")
                        .HasColumnType("int");

                    b.Property<int?>("CustomerIDID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DistrictCodeID")
                        .HasColumnType("int");

                    b.Property<DateTime>("InDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("CityCodeID");

                    b.HasIndex("CustomerIDID");

                    b.HasIndex("DistrictCodeID");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("DKCRM.Core.Entities.Category", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("InDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CategoryName = "Şikayet",
                            InDate = new DateTime(2023, 9, 6, 14, 26, 11, 596, DateTimeKind.Local).AddTicks(4217)
                        });
                });

            modelBuilder.Entity("DKCRM.Core.Entities.City", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("InDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Cities");

                    b.HasDiscriminator<string>("Discriminator").HasValue("City");

                    b.UseTphMappingStrategy();

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Description = "Adana",
                            InDate = new DateTime(2023, 9, 6, 14, 26, 11, 596, DateTimeKind.Local).AddTicks(4203)
                        });
                });

            modelBuilder.Entity("DKCRM.Core.Entities.Customer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("InDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SurName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("DKCRM.Core.Entities.Defination", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("InDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Definations");
                });

            modelBuilder.Entity("DKCRM.Core.Entities.ErrorLog", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("InDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("ErrorLogs");
                });

            modelBuilder.Entity("DKCRM.Core.Entities.Request", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool>("DisplayFlag")
                        .HasColumnType("bit");

                    b.Property<DateTime>("InDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RequestName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Requests");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            DisplayFlag = false,
                            InDate = new DateTime(2023, 9, 6, 14, 26, 11, 596, DateTimeKind.Local).AddTicks(4236),
                            RequestName = "Geç Teslim"
                        });
                });

            modelBuilder.Entity("DKCRM.Core.Entities.SolutionGroup", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool>("DisplayFlag")
                        .HasColumnType("bit");

                    b.Property<DateTime>("InDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SolutionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("SolutionGroups");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            DisplayFlag = true,
                            InDate = new DateTime(2023, 9, 6, 14, 26, 11, 596, DateTimeKind.Local).AddTicks(4249),
                            SolutionName = "BackOffice"
                        });
                });

            modelBuilder.Entity("DKCRM.Core.Entities.Statu", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("InDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("StatuCode")
                        .HasColumnType("int");

                    b.Property<string>("StatuName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Status");
                });

            modelBuilder.Entity("DKCRM.Core.Entities.Telephone", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("CustomerIDID")
                        .HasColumnType("int");

                    b.Property<DateTime>("InDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrefixCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("CustomerIDID");

                    b.ToTable("Telephones");
                });

            modelBuilder.Entity("DKCRM.Core.Entities.Ticket", b =>
                {
                    b.Property<int>("TicketID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TicketID"));

                    b.Property<DateTime>("InDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PersonelIDID")
                        .HasColumnType("int");

                    b.Property<int>("RequestIdID")
                        .HasColumnType("int");

                    b.Property<int>("SolutionIDID")
                        .HasColumnType("int");

                    b.Property<int>("StatuIDID")
                        .HasColumnType("int");

                    b.HasKey("TicketID");

                    b.HasIndex("PersonelIDID");

                    b.HasIndex("RequestIdID");

                    b.HasIndex("SolutionIDID");

                    b.HasIndex("StatuIDID");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("DKCRM.Core.Entities.Ticket_ATT", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("ATTValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("InDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PersonelIDID")
                        .HasColumnType("int");

                    b.Property<int?>("TicketID1")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("PersonelIDID");

                    b.HasIndex("TicketID1");

                    b.ToTable("Ticket_ATTs");
                });

            modelBuilder.Entity("DKCRM.Core.Entities.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("InDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsAgent")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsBO")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SurName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Email = "admin@kapan.com",
                            InDate = new DateTime(2023, 9, 6, 14, 26, 11, 596, DateTimeKind.Local).AddTicks(4054),
                            IsAdmin = true,
                            Name = "Deniz",
                            Password = "010203",
                            SurName = "Kapan"
                        },
                        new
                        {
                            ID = 2,
                            Email = "bo@kapan.com",
                            InDate = new DateTime(2023, 9, 6, 14, 26, 11, 596, DateTimeKind.Local).AddTicks(4068),
                            IsBO = true,
                            Name = "Deniz",
                            Password = "010203",
                            SurName = "Kapan"
                        },
                        new
                        {
                            ID = 3,
                            Email = "agent@kapan.com",
                            InDate = new DateTime(2023, 9, 6, 14, 26, 11, 596, DateTimeKind.Local).AddTicks(4070),
                            IsAgent = true,
                            Name = "Deniz",
                            Password = "010203",
                            SurName = "Kapan"
                        });
                });

            modelBuilder.Entity("DKCRM.Core.Entities.District", b =>
                {
                    b.HasBaseType("DKCRM.Core.Entities.City");

                    b.Property<int>("CityCodeID")
                        .HasColumnType("int");

                    b.Property<int>("DistrictCode")
                        .HasColumnType("int");

                    b.HasIndex("CityCodeID");

                    b.HasDiscriminator().HasValue("District");
                });

            modelBuilder.Entity("DKCRM.Core.Entities.Address", b =>
                {
                    b.HasOne("DKCRM.Core.Entities.City", "CityCode")
                        .WithMany()
                        .HasForeignKey("CityCodeID");

                    b.HasOne("DKCRM.Core.Entities.Customer", "CustomerID")
                        .WithMany()
                        .HasForeignKey("CustomerIDID");

                    b.HasOne("DKCRM.Core.Entities.District", "DistrictCode")
                        .WithMany()
                        .HasForeignKey("DistrictCodeID");

                    b.Navigation("CityCode");

                    b.Navigation("CustomerID");

                    b.Navigation("DistrictCode");
                });

            modelBuilder.Entity("DKCRM.Core.Entities.Telephone", b =>
                {
                    b.HasOne("DKCRM.Core.Entities.Customer", "CustomerID")
                        .WithMany()
                        .HasForeignKey("CustomerIDID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomerID");
                });

            modelBuilder.Entity("DKCRM.Core.Entities.Ticket", b =>
                {
                    b.HasOne("DKCRM.Core.Entities.User", "PersonelID")
                        .WithMany()
                        .HasForeignKey("PersonelIDID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DKCRM.Core.Entities.Request", "RequestId")
                        .WithMany()
                        .HasForeignKey("RequestIdID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DKCRM.Core.Entities.SolutionGroup", "SolutionID")
                        .WithMany()
                        .HasForeignKey("SolutionIDID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DKCRM.Core.Entities.Statu", "StatuID")
                        .WithMany()
                        .HasForeignKey("StatuIDID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PersonelID");

                    b.Navigation("RequestId");

                    b.Navigation("SolutionID");

                    b.Navigation("StatuID");
                });

            modelBuilder.Entity("DKCRM.Core.Entities.Ticket_ATT", b =>
                {
                    b.HasOne("DKCRM.Core.Entities.User", "PersonelID")
                        .WithMany()
                        .HasForeignKey("PersonelIDID");

                    b.HasOne("DKCRM.Core.Entities.Ticket", "TicketID")
                        .WithMany()
                        .HasForeignKey("TicketID1");

                    b.Navigation("PersonelID");

                    b.Navigation("TicketID");
                });

            modelBuilder.Entity("DKCRM.Core.Entities.District", b =>
                {
                    b.HasOne("DKCRM.Core.Entities.City", "CityCode")
                        .WithMany()
                        .HasForeignKey("CityCodeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CityCode");
                });
#pragma warning restore 612, 618
        }
    }
}
