// <auto-generated />
using System;
using DKCRM.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DKCRM.Data.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20230906112401_baslangic")]
    partial class baslangic
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DKCRM.Core.Entities.Address", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("InDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("DKCRM.Core.Entities.Category", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("InDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CategoryName = "Şikayet",
                            InDate = new DateTime(2023, 9, 6, 14, 24, 1, 36, DateTimeKind.Local).AddTicks(5724)
                        });
                });

            modelBuilder.Entity("DKCRM.Core.Entities.City", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("InDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Cities");

                    b.HasDiscriminator<string>("Discriminator").HasValue("City");

                    b.UseTphMappingStrategy();

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Description = "Adana",
                            InDate = new DateTime(2023, 9, 6, 14, 24, 1, 36, DateTimeKind.Local).AddTicks(5708)
                        });
                });

            modelBuilder.Entity("DKCRM.Core.Entities.Customer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("InDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SurName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("DKCRM.Core.Entities.Defination", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("InDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Definations");
                });

            modelBuilder.Entity("DKCRM.Core.Entities.ErrorLog", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("InDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("ErrorLogs");
                });

            modelBuilder.Entity("DKCRM.Core.Entities.Request", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool>("DisplayFlag")
                        .HasColumnType("bit");

                    b.Property<DateTime>("InDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RequestName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Requests");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            DisplayFlag = false,
                            InDate = new DateTime(2023, 9, 6, 14, 24, 1, 36, DateTimeKind.Local).AddTicks(5737),
                            RequestName = "Geç Teslim"
                        });
                });

            modelBuilder.Entity("DKCRM.Core.Entities.SolutionGroup", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool>("DisplayFlag")
                        .HasColumnType("bit");

                    b.Property<DateTime>("InDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SolutionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("SolutionGroups");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            DisplayFlag = true,
                            InDate = new DateTime(2023, 9, 6, 14, 24, 1, 36, DateTimeKind.Local).AddTicks(5751),
                            SolutionName = "BackOffice"
                        });
                });

            modelBuilder.Entity("DKCRM.Core.Entities.Statu", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("InDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("StatuCode")
                        .HasColumnType("int");

                    b.Property<string>("StatuName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Status");
                });

            modelBuilder.Entity("DKCRM.Core.Entities.Telephone", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("InDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrefixCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Telephones");
                });

            modelBuilder.Entity("DKCRM.Core.Entities.Ticket", b =>
                {
                    b.Property<int>("TicketID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TicketID"));

                    b.Property<DateTime>("InDate")
                        .HasColumnType("datetime2");

                    b.HasKey("TicketID");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("DKCRM.Core.Entities.Ticket_ATT", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("ATTValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("InDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Ticket_ATTs");
                });

            modelBuilder.Entity("DKCRM.Core.Entities.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("InDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsAgent")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsBO")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SurName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Email = "admin@kapan.com",
                            InDate = new DateTime(2023, 9, 6, 14, 24, 1, 36, DateTimeKind.Local).AddTicks(5564),
                            IsAdmin = true,
                            Name = "Deniz",
                            Password = "010203",
                            SurName = "Kapan"
                        },
                        new
                        {
                            ID = 2,
                            Email = "bo@kapan.com",
                            InDate = new DateTime(2023, 9, 6, 14, 24, 1, 36, DateTimeKind.Local).AddTicks(5575),
                            IsBO = true,
                            Name = "Deniz",
                            Password = "010203",
                            SurName = "Kapan"
                        },
                        new
                        {
                            ID = 3,
                            Email = "agent@kapan.com",
                            InDate = new DateTime(2023, 9, 6, 14, 24, 1, 36, DateTimeKind.Local).AddTicks(5576),
                            IsAgent = true,
                            Name = "Deniz",
                            Password = "010203",
                            SurName = "Kapan"
                        });
                });

            modelBuilder.Entity("DKCRM.Core.Entities.District", b =>
                {
                    b.HasBaseType("DKCRM.Core.Entities.City");

                    b.Property<int>("DistrictCode")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("District");
                });
#pragma warning restore 612, 618
        }
    }
}
